### ISSUE TITLE
Make pytest run 

### ISSUE THREAD

**Issue by anaschwendler** [cuducos/django-public-admin#1]
Since the tests are not working yet with `pytest`, I'll be tackling this, as @cuducos suggested: maybe using `pytest-django`

**Comment by cuducos** [comment]
> Since there are no tests in the application yet, 

What do you mean? Have you checked the `tests/` directory in the root of the project?

**Comment by anaschwendler** [comment]
> What do you mean?

My bad, sorry me 😅 
What I meant was to make the tests work. When I was writing the issue I kinda just copy and paste the item on the to-do list.

**Comment by cuducos** [comment]
Closed in favor of #3
