### ISSUE TITLE
`models` does not affect the public app

### ISSUE THREAD

**Issue by anapaulagomes** [cuducos/django-public-admin#15]
When having `models=()` and registering the models itself on `public_admin`, it works. All registered models are shown (https://github.com/DadosAbertosDeFeira/maria-quiteria/pull/114/).
Is it a bug or a feature? :sweat_smile: 

```
public_app = PublicApp("datasets", models=())
public_admin = MariaQuiteriaPublicAdminSite(public_apps=public_app)
models_and_admins = [
    (CityCouncilAgenda, CityCouncilAgendaAdmin),
    (CityCouncilAttendanceList, CityCouncilAttendanceListAdmin),
    (CityCouncilExpense, CityCouncilExpenseAdmin),
    (CityCouncilMinute, CityCouncilMinuteAdmin),
    (Gazette, GazetteAdmin),
    (CityHallBid, CityHallBidAdmin),
]

for model, admin in models_and_admins:
    public_admin.register(model, admin)
```

**Comment by cuducos** [comment]
Definitively a bug :bug:!

Also, a reflection of the _alpha_ status of this package. As far as I remember, the models declared in the `PublicApp` are mostly used to:

* hack Django’s permission system and block access to non-declared models (not necessarily related to views at this point)
* highjack and remove from the `AdminSite` the URLs related to these models

I have to dedicate some time to replicate this bug and understand a few things before thinking about a possible solution, but I think something to explore is to have our own `register` method that does this verification.
