### ISSUE TITLE
Remove recent actions box

### ISSUE THREAD

**Issue by anapaulagomes** [cuducos/django-public-admin#19]
Since the `django-admin` is public and no actions are taken by users, it makes sense to get the box "Recent Actions" removed.

![](https://user-images.githubusercontent.com/4131432/82030998-7e384100-9699-11ea-8b05-933429e4fcad.png)

According to @cuducos's tip [here](https://github.com/DadosAbertosDeFeira/maria-quiteria/issues/115#issuecomment-631768444), we can get it done by using `display: none`: [this template](https://github.com/okfn-brasil/serenata-de-amor/blob/master/jarbas/dashboard/templates/admin/base_site.html) uses `dashboard.css` that has a [`display: none`](https://github.com/okfn-brasil/serenata-de-amor/blob/128bd2f85abb7c55dbf9b0152e70e908d316f9e5/jarbas/dashboard/static/dashboard.css#L5-L7).

**Comment by jhrdt** [comment]
Hej,

I tried to solve this issue in a other way, with Django templates. 
Take a look at PR #20 .
