### ISSUE TITLE
`Recent actions` not hidden

### ISSUE THREAD

**Issue by lsmith77** [cuducos/django-public-admin#25]
I added `public_admin` above `django.contrib.admin` as instructed on https://django-public-admin.readthedocs.io/en/latest/usage.html#templates

<img width="212" alt="image" src="https://github.com/cuducos/django-public-admin/assets/300279/eacdad36-cb43-48ef-8e90-f4c178393ffa">

But I am still getting the recent actions shown:
<img width="196" alt="image" src="https://github.com/cuducos/django-public-admin/assets/300279/6478c826-9ac6-4a23-81b7-b44fdc8080a7">

**Comment by cuducos** [comment]
I am not able to reproduce it. Can you share a way to do it?

What I have tried is the `example/` from this repo:

```console
$ git clone https://github.com/cuducos/django-public-admin.git
$ cd django-public-admin
$ poetry update  # and I removed pip from pyproject.toml, gonna find a fix later
$ poetry run python manage.py runserver
```

And then visited the dashboard at http://127.0.0.1:8000/dashboard/

<img width="1448" alt="image" src="https://github.com/cuducos/django-public-admin/assets/4732915/7378871f-db1d-49d0-8081-49432651c8c6">

**Comment by lsmith77** [comment]
Thanks for looking into this.

Something is strange in my setup, since I can override `base_site.html` but `index.html` doesn't seem to register any changes.

**Comment by lsmith77** [comment]
OK the issue is due to using grappelli

I am looking into how to get grappelli's dashboard's to work with public_admin:
https://django-grappelli.readthedocs.io/en/latest/dashboard_setup.html?highlight=dashboard#custom-dashboard

**Comment by lsmith77** [comment]
FYI I got it to work

```
GRAPPELLI_INDEX_DASHBOARD = {
    "django.contrib.admin.site": "rules.dashboard.CustomIndexDashboard",
    "word_lists.public_admin.public_admin": "word_lists.dashboard.CustomIndexDashboard",
}
```

My public site sits in `word_lists/public_admin/py`.
