### ISSUE TITLE
Override site metadata

### ISSUE THREAD

**Issue by lsmith77** [cuducos/django-public-admin#26]
For admin I can override the site metadata as follows:

```
admin.site.site_header = 'your_header'
admin.site.site_title = 'site_title'
admin.site.index_title = 'index_title'
```

But it seems like `public_admin` has not `site`. Is there a way to adjust this metadata?

**Comment by lsmith77** [comment]
I can actually do the following:

```
public_admin.site_header = 'your_header'
public_admin.site_title = 'site_title'
public_admin.index_title = 'index_title'
```

But it seems to have no effect.

**Comment by lsmith77** [comment]
Actually nevermind .. sorry for the noise. It works :)
Should I submit this as a doc PR?

**Comment by cuducos** [comment]
How have you sorted that out? Can you share here?

**Comment by lsmith77** [comment]
It works exactly like this:
https://github.com/cuducos/django-public-admin/issues/26#issuecomment-1864853299

**Comment by cuducos** [comment]
Ah, ok. So, since it's Django standard I don't think we need extra docs on that. Thank you so much : )
