### ISSUE TITLE
Add tox

### ISSUE THREAD

**Issue by cuducos** [cuducos/django-public-admin#5]
Depends on #3.

[`tox`](https://pypi.org/project/tox/) will be useful to test this with different versions of Python (from 3.6 to 3.8) and of Django (2 and 3).

**Comment by anapaulagomes** [comment]
Can I work on this one? 😬

**Comment by cuducos** [comment]
Sure thing!

I'm reviewing #11 (#3 implementation) later today. But if you want you can pull that branch and we review, test and merge both the implementations for #3 and #5 in the same PR. No problems from my side, since #11 looks really good (thanks @anaschwendler) and I just need to test it locally before mergeing it.

**Comment by cuducos** [comment]
#11 merged.
You can get started at `master` now ; )
