### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by cuducos** [cuducos/django-public-admin#6]
Add GitHub Actions to:

- [ ] Run tests using `tox` (depends on #5)
- [ ] Run [Black](https://github.com/psf/black) and [`flake8`](https://pypi.org/project/flake8/) checks

**Comment by cuducos** [comment]
I tried to get this started with ced9ccc, but it fails.

**Comment by anapaulagomes** [comment]
I thought that the Pip package [tox-gh-actions](https://pypi.org/project/tox-gh-actions/) may interest whoever decide to tackle this issue. An example of tox+GithubActions (and this package) [here](https://github.com/model-bakers/model_bakery/pull/89/files#).
